### ISSUE TITLE
Crashes when adding/changing books

### ISSUE THREAD

**Issue by piotrdrag** [mvz/alexandria-book-collection-manager#106]
When clicking Add in the Adding a Book dialog: [alex crash adding book.txt](https://github.com/mvz/alexandria-book-collection-manager/files/5684513/alex.crash.adding.book.txt). Cover doesn’t get saved, if one was provided.

When clicking Save in the Properties for 'Book' dialog: [alex crash saving with cover.txt](https://github.com/mvz/alexandria-book-collection-manager/files/5684514/alex.crash.saving.with.cover.txt). Cover gets saved, if one was provided.

`alexandria-0.7.8-1.fc33.noarch`

**Comment by mvz** [comment]
I'm afraid I can't reproduce this. It may be best to report this issue to the Fedora maintainer.

**Comment by piotrdrag** [comment]
Thanks, reported as https://bugzilla.redhat.com/show_bug.cgi?id=1909500

**Comment by piotrdrag** [comment]
So, I now have more specific reproduction steps, maybe it could help you find the issue:

1. Type anything in the search bar.
2. Click Library → Add Book Manually.
2. Fill out the form.
3. Click the Add button.
4. App crashes.

Without the first step, Alexandria won’t crash.

**Comment by mtasaka** [comment]
> So, I now have more specific reproduction steps, maybe it could help you find the issue:
>     1. Type anything in the search bar.
>     2. Click Library → Add Book Manually.
>     3. Fill out the form.
>     4. Click the Add button.
>     5. App crashes.
> 
> Without the first step, Alexandria won’t crash.

Reproducible with Fedora alexandria-0.7.8-1.fc33.noarch .  
I guess with 1. Type anything in the search bar, `on_toolbar_filter_entry_changed` is called
https://github.com/mvz/alexandria-book-collection-manager/blob/v0.7.8/lib/alexandria/ui/callbacks.rb#L95
 and book entry is restricted by the result of the search.  
Then with 4. i.e. when adding adding a book really, alexandria tries to do `select_a_book(book)`
https://github.com/mvz/alexandria-book-collection-manager/blob/v0.7.8/lib/alexandria/ui/ui_manager.rb#L572
, however actually there is no correspoding book in the current view (because list is restricted by search),  so in `select_book_in_view` , `path` is nil:
https://github.com/mvz/alexandria-book-collection-manager/blob/v0.7.8/lib/alexandria/ui/ui_manager.rb#L1195
and the crash we see here happens.

One workaround seems to explicitly clear the search text when adding book.

**Comment by mtasaka** [comment]
Line number may differ
```
diff -urp alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/ui_manager.rb alexandria-book-collection-manager-0.7.8.new/lib/alexandria/ui/ui_manager.rb
--- alexandria-book-collection-manager-0.7.8/lib/alexandria/ui/ui_manager.rb    2021-03-05 00:06:46.604012398 +0900
+++ alexandria-book-collection-manager-0.7.8.new/lib/alexandria/ui/ui_manager.rb        2021-03-04 23:53:11.560895622 +0900
@@ -569,7 +569,10 @@ module Alexandria
           end
           @iconview.unfreeze
           @listview.unfreeze # NEW
-          select_a_book(book) if [Library::BOOK_ADDED, Library::BOOK_UPDATED].include? kind
+          if [Library::BOOK_ADDED, Library::BOOK_UPDATED].include? kind
+            on_clear_search_results
+            select_a_book(book) 
+          end
         elsif selected_library.is_a?(SmartLibrary)
           refresh_books
         end
```

**Comment by mvz** [comment]
Thanks @piotrdrag and @mtasaka for figuring out what the problem was.
